name: Build and Deploy LaTeX Document

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Compile the LaTeX document using a dedicated LaTeX action.
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Introduction-to-Kotlin.tex

      # Create a folder to hold published artifacts
      - name: Prepare gh-pages directory
        run: mkdir -p gh-pages

      # Move the compiled PDF to the deployment directory.
      - name: Move PDF to gh-pages directory
        run: mv Introduction-to-Kotlin.pdf gh-pages/
      
      # Create a simple index.html to redirect to the PDF
      - name: Create redirect to PDF
        run: |
          echo '<html><head><meta http-equiv="refresh" content="0; url=Introduction-to-Kotlin.pdf"></head></html>' > gh-pages/index.html

      # Deploy the content of the 'gh-pages' folder to the gh-pages branch.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
